name: CI Pipeline

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore .NET dependencies
      run: dotnet restore '**/*.csproj'

    - name: Build .NET application
      run: dotnet build '**/*.csproj' --configuration Release

    - name: Publish .NET application
      run: dotnet publish '**/*.csproj' --configuration Release --output ${{ github.workspace }}/drop/api

    - name: Install dotnet-ef tool
      run: dotnet tool install dotnet-ef --version 8.0.0 --global

    - name: Apply EF Core Migrations
      run: dotnet ef database update --project './DealmateApi/DealmateApi.csproj' --connection "Host=${{ env.DB_HOST }};Database=${{ env.DB_NAME }};Username=${{ env.DB_USER }};Password=${{ env.DB_PASSWORD }};SslMode=${{ env.DB_SSLMODE }};"
      env:
        PATH: ${{ env.PATH }}:${{ runner.tool_cache }}/dotnet/tools

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install and Build UI
      working-directory: 'ui'
      run: |
        yarn install
        yarn global add env-cmd
        yarn build

    - name: Set Environment for UI
      working-directory: 'ui'
      run: yarn build:prod

    - name: Run ESLint
      working-directory: 'ui'
      run: yarn eslint src/ --max-warnings=0

    - name: Run Jest tests
      working-directory: 'ui'
      run: yarn test:ci

    - name: Move UI Build to Drop Folder
      run: cp -r ui/build/* ${{ github.workspace }}/drop/ui

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: drop

    - name: Run .NET Unit Tests
      run: dotnet test './DealmateUnitTest/DealmateUnitTest.csproj'
